### ISSUE TITLE
Fix pathes.bat and add task for running it with a parameter

### ISSUE THREAD

**Issue by GRPilot** [GRPilot/lazycoder#8]
You have to add a task in tasks.json for running pathes.bat.

Add scripts for updating c_cpp_properties.json from pathes.bat as it already working with launch.json

**Comment by GRPilot** [comment]
You can also make the pathes.bat for yourself. It's so easy:
add pathes.custom.bat and add this file into gitignore. Then, change the pathes.bat logic so that it loads the paths from a custom file, but if it doesn't exist, error throwing or something the same

**Comment by seigtm** [comment]
Added c_cpp_properties.json generation and more.
